# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='skill_set',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='other_info',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='qualification',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='skill_set',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='company_name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='qualification',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='skill_set',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
