# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20180730_0655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='skill_set',
            new_name='job_description',
        ),
        migrations.AddField(
            model_name='jobs',
            name='jobtilte',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='jobs',
            name='req_exp',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='jobs',
            name='req_skill_set',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
