# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20180730_0726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='jobtilte',
            new_name='jobtitle',
        ),
    ]
