# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20180730_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='company_name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
