# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 10:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_jobs_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_applications',
            name='jobSeeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
